TESTS = [
    'MouseEvent',
    'KeyboardEvent',
    'Active'
]

Import('env', 'SOURCES')
FIXED_SOURCES = []
for s in SOURCES:
    FIXED_SOURCES.append('../' + s)

for t in TESTS:
    l = list(FIXED_SOURCES)
    l.append(t + '.cc');
    env.Program(target=('bin/' + t), source=l)
